=== Raugharr/MekWars/MekWarsServer/server-dist/data/factions.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Jon Schattke (Scahttke Computer Services) -->
<!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)-->
<!ELEMENT faction-array (FACTION+)>
<!ELEMENT faction (name, money, color, abbreviation, type, logo, baseGunner, basePilot, conquerable, inHouseAttacks, mayUseBM, housePlayerColor, defectTo, defectFrom)>

<!ELEMENT name (#PCDATA)>
<!ELEMENT money (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT abbreviation (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT baseGunner (#PCDATA)>
<!ELEMENT basePilot (#PCDATA)>
<!ELEMENT conquerable (#PCDATA)>
<!ELEMENT inHouseAttacks (#PCDATA)>
<!ELEMENT mayUseBM (#PCDATA)>
<!ELEMENT housePlayerColor (#PCDATA)>
<!ELEMENT defectTo (#PCDATA)>
<!ELEMENT defectFrom (#PCDATA)>

=== Raugharr/MekWars/MekWarsServer/server-dist/data/factions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DOCUMENT SYSTEM "factions.dtd">
<faction-array>
	<faction>
		<name>Davion</name>
		<money>180</money>
		<color>#808000</color>
		<abbreviation>D</abbreviation>
		<type>House</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#808000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Steiner</name>
		<color>#0000ff</color>
		<abbreviation>S</abbreviation>
		<type>House</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#0000ff</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Liao</name>
		<color>#004000</color>
		<abbreviation>L</abbreviation>
		<type>House</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#004000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Marik</name>
		<color>#800080</color>
		<abbreviation>M</abbreviation>
		<type>House</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Kurita</name>
		<color>#ff0000</color>
		<abbreviation>K</abbreviation>
		<type>House</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Periphery</name>
		<color>#333333</color>
		<abbreviation>P</abbreviation>
		<type>House</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Northwind Highlanders</name>
		<color>#008000</color>
		<abbreviation>HL</abbreviation>
		<type>Mercenary</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Wolfs Dragoons</name>
		<color>#800000</color>
		<abbreviation>WD</abbreviation>
		<type>Mercenary</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Hansens Roughriders</name>
		<color>#b0c4de</color>
		<abbreviation>HRR</abbreviation>
		<type>Mercenary</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Kell Hounds</name>
		<color>#990000</color>
		<abbreviation>KH</abbreviation>
		<type>Mercenary</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Gray Death Legion</name>
		<color>#990000</color>
		<abbreviation>GDL</abbreviation>
		<type>Mercenary</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Comstar</name>
		<color>#663300</color>
		<abbreviation>COM</abbreviation>
		<type>House</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>true</conquerable>
		<inHouseAttacks>false</inHouseAttacks>
		<mayUseBM>true</mayUseBM>
		<housePlayerColor>#ff0000</housePlayerColor>
		<defectTo>true</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
	<faction>
		<name>Solaris Training Company</name>
		<color>#33CCCC</color>
		<abbreviation>SOL</abbreviation>
		<type>Newbie</type>
		<logo>http://www.megamek.com/NoLogo.jpg</logo>
		<baseGunner>4</baseGunner>
		<basePilot>5</basePilot>
		<conquerable>false</conquerable>
		<inHouseAttacks>true</inHouseAttacks>
		<mayUseBM>false</mayUseBM>
		<housePlayerColor>#33CCCC</housePlayerColor>
		<defectTo>false</defectTo>
		<defectFrom>true</defectFrom>
	</faction>
</faction-array>
